Add Playwright GitHub Actions workflow

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -20,10 +20,14 @@ jobs:
     - name: Install Playwright Browsers
       run: npx playwright install --with-deps
     - name: Run Playwright tests
-      #run: npx playwright test --project=Chromium  --workers 1
-      run: npx playwright test smokeTest.spec.ts --project=Chromium  --workers 1
+      run: npx playwright test smokeTest.spec.ts --project=Chromium --workers 1
+    - name: Verify Playwright Report Exists
+      run: |
+        if [ ! -d "playwright-report" ]; then
+          echo "Playwright report directory not found!"
+          exit 1
+        fi
     - uses: actions/upload-artifact@v3.1.3
-
       if: always()
       with:
         name: playwright-report
